### ISSUE TITLE
Publication checklist

### ISSUE THREAD

**Issue by SamuelYvon** [udem-dlteam/mimosa#87]
Todo before Friday:

- [ ] Open source this repo
- [ ] Fork / Copy / Transfer Ownership of https://github.com/SamuelYvon/gambit in this org
- [x] Change the links from the paper to the previously forked repo
- [x] Determine if github repos need to be anonymized in the paper?
